nelmio_cors:
  defaults:
    allow_credentials: false
    expose_headers: []
    max_age: 0
    hosts: []
    allow_origin: [ '*' ]
    allow_headers: ['*']
    allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE','PATCH' ]
